# Generated by Django 4.1.1 on 2022-10-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='features_product',
            new_name='featured_product',
        ),
    ]
